### ISSUE TITLE
Info about difference with `charm kv`

### ISSUE THREAD

**Issue by onderweg** [charmbracelet/skate#18]
What I miss in the readme, is a bit of explanation what the difference is between `skate` and the `charm kv` command.

They seem mostly the same.
The only difference I can see, by doing a `charm fs tree`, is that they create different files. So assume the database they use is the only difference?
Would be nice to see some background info in the readme.

**Comment by bashbunni** [comment]
Hey onderweg, 

That's right, `charm kv` and `skate` do the same things. The only functional difference is that skate uses a separate database. I'll work on adding that to the docs. Thank you for the feedback!

**Comment by bashbunni** [comment]
This has been added to the README and merged to main. Feel free to re-open if the bit about `charm kv` in the README is unclear!

**Comment by onderweg** [comment]
Thanks! Looks clear.
