### ISSUE TITLE
what is i lose my device?

### ISSUE THREAD

**Issue by pvinis** [charmbracelet/skate#20]
then i can never access my data again?

in this thought experiment, i have not linked any other device.

**Comment by toby** [comment]
Hi @pvinis for now you can `charm backup-keys` with the https://github.com/charmbracelet/charm binary. We plan to do even more to secure your identity, but this is worth doing now as a first step!

**Comment by bashbunni** [comment]
Need to add this to docs

**Comment by bashbunni** [comment]
Added more explicit info on backups to [charm](https://github.com/charmbracelet/charm) which is where you would be managing your `charm` account that gets used with `skate`
