### ISSUE TITLE
Ehancement: Improve skate list

### ISSUE THREAD

**Issue by harsha3294** [charmbracelet/skate#25]
if we have some keys that got set from files

like
```
 skate set key1 < test1.log
 skate set key2 < test2.log
```

When we do skate list , it is very cumbersome to look it since the entire file contents will be displayed for all such files.

Instead either provide:

skate list keys ===> only display keys
or 
skate list  ===> should not display the value of multi-line values and only show them when requested using skate get key1 or something like that. 

for example look at the following output:
It is hard to figure out which is the key and which is the value.

memutil	
fda
 GROUP STATS: Mon Jan 25 22:26:13 2021
   Start Group ID   : 0
   No. of levels    : 12
   Unit             : MB
   Inclusion filter : (all)
   Exclusion filter : (none)
   Selected columns : gid:name:parGid:min:max:eMin:flags

**Comment by nat-418** [comment]
similarly it would be nice to be able to list databases

**Comment by toby** [comment]
@nat-418 I opened a [new issue](https://github.com/charmbracelet/skate/issues/26) for listing databases.

@harsha3294 thanks for opening this, as mentioned in slack, `skate list` supports the following flags/options:

```
skate list -h
List key value pairs with an optional @ db.

Usage:
   list [@DB] [flags]

Flags:
  -d, --delimiter string   delimiter to separate keys and values (default "\t")
  -h, --help               help for list
  -k, --keys-only          only print keys and don't fetch values from the db
  -r, --reverse            list in reverse lexicographic order
  -b, --show-binary        print binary values
  -v, --values-only        only print values
```
