### ISSUE TITLE
List databases

### ISSUE THREAD

**Issue by toby** [charmbracelet/skate#26]
Right now `skate` can list keys, values and key value pairs but there is no way to list which databases have been created with the `skate key@DATABASE value` syntax. We should support that though.

**Comment by kodumbeats** [comment]
I've cobbled together a small patch to read the directories from the filesystem, but I think the implementation would be cleaner in `charm/kv` instead (easier access to fs)? Happy to open this up as a PR for further discussion:

https://github.com/charmbracelet/skate/compare/main...kodumbeats:feat-list-databases
