### ISSUE TITLE
list-dbs command 

### ISSUE THREAD

**Issue by dieboljo** [charmbracelet/skate#32]
The `list-dbs` command, which is briefly referenced in the README, does not work. 

I'm using the latest version (v0.1.5), installed on Arch via Pacman. I also attempted to run the command through the Docker image.

Here is my input and output:
```
$ skate list-dbs
Error: unknown command "list-dbs" for ""
```

This greatly limits the usefulness of the program, since I would then need to use a separate file/database to keep track of the `skate` databases...

Notably, this command is absent in the output of `skate --help`:
```
Usage:
   [flags]
   [command]

Available Commands:
  delete      Delete a key with an optional @ db.
  get         Get a value for a key with an optional @ db.
  help        Help about any command
  link        Link multiple machines to your Charm account
  list        List key value pairs with an optional @ db.
  reset       Delete local db and pull down fresh copy from Charm Cloud.
  set         Set a value for a key with an optional @ db.
  sync        Sync local db with latest Charm Cloud db.

Flags:
  -h, --help      help for this command
  -v, --version   version for this command

Use " [command] --help" for more information about a command.
```

**Comment by toby** [comment]
Hi, `skate list-dbs` is in the `main` branch but hasn't been released yet. There's still a small bug where it will list non-db files that I intend to fix this week before the release, but if you want to play with it, you can checkout the code and `go build`.

**Comment by toby** [comment]
Hi, this is released now and should be showing up in package managers shortly:

https://github.com/charmbracelet/skate/releases/tag/v0.2.0
