### ISSUE TITLE
No release tarball for amd64?

### ISSUE THREAD

**Issue by eggbean** [charmbracelet/skate#51]
Hi. In releases, why isn't there a tarball for the amd64 build? There is one for every other architecture (apart from the fringe 386). The most popular architecture is surely amd64?

### Missing files:
* skate_0.2.1_linux_386.tar.gz
* skate_0.2.1_linux_386.tar.gz.sbom
* skate_0.2.1_linux_arm64.tar.gz
* skate_0.2.1_linux_arm64.tar.gz.sbom

I would like to have an amd64 tarball if possible, ideally. I'm going to have to extract from the debian package in my workflow for the time being, but could this please be added?

**Comment by eggbean** [comment]
I assumed that the .sbom files were file checksums, but they aren't so I'm not bothered about those.

**Comment by caarlos0** [comment]
Are you looking at some specific releases? 

In the latest all are there:
- the archives are there, named `x86_64`
- arm64 and i386 are also available

**Comment by eggbean** [comment]
Hi @caarlos0. There aren't tarballs though? Just for `.apk`, `.deb` and `.rpm`. No `.tar.gz` like with the other architecture (apart from i386).

At the moment I am just extracting the binary from the `.deb` package like this:

    dpkg-deb --fsys-tarfile skate_*_linux_amd64.deb | tar xOf - ./usr/bin/skate > skate
    chmod +x skate

..which is a bit mad.

**Comment by caarlos0** [comment]
It is there: https://github.com/charmbracelet/skate/releases/download/v0.2.1/skate_0.2.1_linux_x86_64.tar.gz

**Comment by eggbean** [comment]
Ah, I see. I was looking at the `amd64` files. I'm used to seeing either `amd64` and `arm64` or `x86_64` and `aarch64` (which is bit easier to differentiate). Debian vs RedHat thing I think. Sorry about that, cheers.
