### ISSUE TITLE
Is it really fully encrypted ?

### ISSUE THREAD

**Issue by craph** [charmbracelet/skate#58]
Hello,

I wondering if the code of `skate` is really fully encrypted like it's mentioned in the README.md file because in the source code it's using the method `OpenWithDefaults`  https://github.com/charmbracelet/skate/blob/main/main.go#L304  and doesn't refers to `OptionsWithEncryption` like it is here https://github.com/charmbracelet/charm/blob/main/kv/client.go#L171

Can you explain how it's working ?

Thank you very much.

**Comment by toby** [comment]
Hi! Thanks for reaching out. `OpenWithDefaults` calls `Open`:

https://github.com/charmbracelet/charm/blob/main/kv/kv.go#L68

Which in turn calls `openDB`:

https://github.com/charmbracelet/charm/blob/main/kv/kv.go#L34

Which calls `OptionsWithEncryption`:

https://github.com/charmbracelet/charm/blob/main/kv/client.go#L171

Hope that helps. Always happy to chat about the details in Discord too: https://charm.sh/chat
